[workspace]
members = ["packages/cursus", "packages/cursus-bin"]
resolver = "3"

[workspace.package]
version = "0.9.3"
edition = "2024"
license = "MPL-2.0"

[workspace.lints.rust]
unreachable_pub = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(coverage)", "cfg(coverage_nightly)"] }

[workspace.lints.clippy]
excessive_nesting = "warn"
too_many_lines = "warn"
