[config]
default_to_workspace = false

# Coverage disabled due to upstream LLVM bug: https://github.com/llvm/llvm-project/pull/189270
[tasks.coverage]
clear = true
command = "cargo"
args = ["test", "--workspace"]

[tasks.coverage-html]
clear = true
command = "cargo"
args = ["test", "--workspace"]

[tasks.release-linux-x86_64]
command = "cargo"
args = ["zigbuild", "--release", "-p", "cursus-bin", "--target", "x86_64-unknown-linux-musl"]

[tasks.release-linux-aarch64]
command = "cargo"
args = ["zigbuild", "--release", "-p", "cursus-bin", "--target", "aarch64-unknown-linux-musl"]

[tasks.release-linux-riscv64]
command = "cargo"
args = ["zigbuild", "--release", "-p", "cursus-bin", "--target", "riscv64gc-unknown-linux-musl"]

[tasks.release-linux]
dependencies = ["release-linux-x86_64", "release-linux-aarch64", "release-linux-riscv64"]

[tasks.release-macos-x86_64]
command = "cargo"
args = ["zigbuild", "--release", "-p", "cursus-bin", "--target", "x86_64-apple-darwin"]

[tasks.release-macos-aarch64]
command = "cargo"
args = ["zigbuild", "--release", "-p", "cursus-bin", "--target", "aarch64-apple-darwin"]

[tasks.release-macos]
dependencies = ["release-macos-x86_64", "release-macos-aarch64"]

[tasks.release-windows-x86_64]
command = "cargo"
args = ["zigbuild", "--release", "-p", "cursus-bin", "--target", "x86_64-pc-windows-gnullvm"]

[tasks.release-windows-aarch64]
command = "cargo"
args = ["zigbuild", "--release", "-p", "cursus-bin", "--target", "aarch64-pc-windows-gnullvm"]

[tasks.release-windows]
dependencies = ["release-windows-x86_64", "release-windows-aarch64"]

[tasks.release-cross]
dependencies = ["release-linux", "release-windows"]

[tasks.release]
dependencies = ["release-linux", "release-macos", "release-windows"]
