[npm]
enabled = true
path = "pkg/"

[cargo]
enabled = true

[github]
enabled = true
build_command = "cargo make release"

[github.artifacts]
chronicle-linux-x86_64 = "target/x86_64-unknown-linux-musl/release/chronicle"
chronicle-linux-aarch64 = "target/aarch64-unknown-linux-musl/release/chronicle"
chronicle-linux-riscv64gc = "target/riscv64gc-unknown-linux-musl/release/chronicle"
chronicle-osx-x86_64 = "target/x86_64-apple-darwin/release/chronicle"
chronicle-osx-aarch64 = "target/aarch64-apple-darwin/release/chronicle"
chronicle-windows-x86_64 = "target/x86_64-pc-windows-gnullvm/release/chronicle.exe"
chronicle-windows-aarch64 = "target/aarch64-pc-windows-gnullvm/release/chronicle.exe"
